language: 
 — ruby
rvm:
 — 2.7.2
cache:
 — bundler
script:
 — bundle install
 — bin/rails db:create
 — bin/rails db:migrate
 — bundle exec rspec
services:
 — postgresql
# deployment details - add while setting up Heroku 
deploy:
  provider: heroku
 api_key:
  secure: "AQ/g3ZOpF6bUb4GKVySaUJDSQaTXtsnYttAGmTlWIbB+/n5oFQL53n3WgPV3czftj3xfxRERyvcb3mQO1i1VDwsv74/MJk295IYCUK7Z+LB7F/lO2lvXlrOf7NPVkVdea65xmzs5+9+22kX8l+KRSQN2ReG/WhOhLKF84rqqsGh4SyhczoB2bpUAT3MVNHk710BlgrGKrRPGx2urZNd/lt5MAb8aBGMw+cDLGZvytlpk1OdcrXZMC8KqRV+Hjx14hsfSldCX2bbfV7zpXkbIBDP+ZejafVxi2AXdS/K1fT2LEVDL+v4Q8gKk0JRMDIHwsfvqJ7RFKai9aZx2GwmKGzcmNt31DBk6KxhLRzHMZI3i+HFnT9xbgsJqmfkMgb/5qIjz4/MiA4EDKYJMCEcBF9Zzb8+jOwbrv+X2R8ap3KP0H/Qt7IzlL7kgBh0JEnCawXZGBZRXDFyKVkNQTcpdRAOE2OBxRbFrQuYTTkNBWUY0yv6993PRa6/ae60UryUzVluG5j+Ek5PDFnAkfP8rFciDkjGeqTMg661l6JFYAKfHK0cNjWT3WrSxuPMmJ3HzJY/9yl0fsArOR5N7QN5PY2T36za0gXxcVKZc5Ruh3cKEBmtqRsfmdlqumrAksMx2aQLfYw/PEpOdC3yoTQsSeTbcwLXIYavQp+82+fmjcBg="
app: relational-rails
  on:
 repo: matt-kragen/Relational_Rails

